import React, { useState, useRef, useEffect } from 'react';
import Header from './components/Header';
import ValuationForm from './components/ValuationForm';
import ValuationResult from './components/ValuationResult';
import { PropertyDetails, ValuationResponse } from './types';
import { getValuation } from './services/localValuationService'; // Changed import

const App = () => {
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<ValuationResponse | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [currentInput, setCurrentInput] = useState<PropertyDetails | null>(null);
  const [initialFormData, setInitialFormData] = useState<PropertyDetails | null>(null);
  const resultRef = useRef<HTMLDivElement>(null);

  const handleValuationSubmit = async (details: PropertyDetails) => {
    setLoading(true);
    setError(null);
    setResult(null);
    setCurrentInput(details);

    try {
      const valuationResponse = await getValuation(details); // No need for artificial delay now, service has it
      setResult(valuationResponse);
      setTimeout(() => {
        resultRef.current?.scrollIntoView({ behavior: 'smooth', block: 'start' });
      }, 300);
    } catch (err: any) {
      console.error(err);
      setError("Failed to generate valuation. An unexpected error occurred during calculation."); // General error message
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    const params = new URLSearchParams(window.location.search);
    const city = params.get('city');
    const year = params.get('year');
    const price = params.get('price');
    const size = params.get('size');
    
    if (city && year && price && size) {
       const details: PropertyDetails = {
         city,
         yearPurchased: Number(year),
         originalPrice: Number(price),
         squareFootage: Number(size),
         projectName: params.get('project') || undefined,
         bedrooms: params.get('beds') || undefined
       };
       setInitialFormData(details);
       handleValuationSubmit(details);
    }
  }, []);

  return (
    <div className="min-h-screen bg-gray-50 text-gray-900 pb-20 font-sans">
      <Header />
      
      <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-10 space-y-12">
        <div className="text-center max-w-3xl mx-auto space-y-4">
          <h2 className="text-4xl font-extrabold text-gray-900 tracking-tight sm:text-5xl mb-4">
            How much is your <br className="hidden sm:block" />
            <span className="text-blue-600">assignment condo</span> worth?
          </h2>
          <p className="text-lg text-gray-600">
            Get an instant algorithmic valuation for your pre-construction purchase in the Greater Toronto Area.
          </p>
        </div>

        <div className="max-w-3xl mx-auto">
          <ValuationForm 
            onSubmit={handleValuationSubmit} 
            isLoading={loading} 
            initialData={initialFormData} 
          />
        </div>

        {error && (
          <div className="max-w-3xl mx-auto bg-red-50 text-red-700 p-4 rounded-lg border border-red-200 text-center flex flex-col items-center gap-2">
            <span className="font-bold">Error:</span>
            <span>{error}</span>
          </div>
        )}

        {result && currentInput && (
          <div ref={resultRef} className="pt-8 border-t border-gray-200">
             <div className="flex items-center justify-between mb-8 px-2">
                <h3 className="text-2xl font-bold text-gray-900">Valuation Report for {currentInput.projectName || 'Property'}</h3>
             </div>
             <ValuationResult 
               data={result.data} 
               sources={result.sources} 
               input={currentInput}
             />
          </div>
        )}
      </main>

      <footer className="border-t border-gray-200 bg-white py-12 mt-12">
        <div className="max-w-7xl mx-auto px-4 text-center text-gray-500 text-sm">
          <p>&copy; {new Date().getFullYear()} CondoValuate GTA. All rights reserved.</p>
          <p className="mt-2 text-xs text-gray-400 max-w-2xl mx-auto">
            Disclaimer: Estimates are for informational purposes only and generated by an algorithm based on general market trends. 
            Real estate values are highly volatile. This is not financial advice or a professional appraisal.
          </p>
        </div>
      </footer>
    </div>
  );
};

export default App;